import { useEffect, useState, type ComponentType } from 'react'
import { BarChart3, Bell, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Code2, FolderKanban, Grid2X2, ListChecks, Menu, MoreVertical, Plus, Search, Settings as SettingsIcon, Sparkles, Sun, Timer, UserRound, X } from 'lucide-react'
import './App.css'
import { ThemeProvider, useTheme, type Theme } from './contexts/ThemeContext'
import { TaskManagerPage } from './pages/TaskManagerPage'
import { DailyPlannerPage } from './pages/DailyPlannerPage'
import { DsaTrackerPage } from './pages/DsaTrackerPage'
import { taskService } from './services/taskService'
import type { Task } from './types/task'

type Icon = ComponentType<{ size?: number; strokeWidth?: number; className?: string }>
type Nav = { label:string; path:string; icon:Icon }
const nav: Nav[] = [
  {label:'Dashboard',path:'/dashboard',icon:Grid2X2},{label:'Daily Planner',path:'/daily-planner',icon:CalendarDays},{label:'DSA Tracker',path:'/dsa-tracker',icon:Code2},{label:'Project Tracker',path:'/project-tracker',icon:FolderKanban},{label:'Focus Timer',path:'/focus-timer',icon:Timer},{label:'Analytics',path:'/analytics',icon:BarChart3},{label:'Settings',path:'/settings',icon:SettingsIcon},
]
const pages: Record<string,[string,string]> = {'/daily-planner':['Daily Planner','Plan your day with intention and make room for meaningful work.'],'/dsa-tracker':['DSA Tracker','Turn focused practice into lasting problem-solving confidence.'],'/learning-tracker':['Learning Tracker','See your learning journey take shape, one thoughtful session at a time.'],'/habit-tracker':['Habit Tracker','Build small rituals that steadily move you toward your goals.'],'/project-tracker':['Project Tracker','Keep your best ideas, milestones, and momentum in one calm space.'],'/focus-timer':['Focus Timer','Create a distraction-free ritual for your most important work.'],'/calendar':['Calendar','Bring your commitments and study flow into a single clear view.'],'/analytics':['Analytics','Discover the patterns behind your productive days.'],'/notes':['Notes','Capture ideas before they disappear, then connect them to your learning.']}
const go=(p:string)=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
const I=({icon:Icon,size=18}:{icon:Icon;size?:number})=><Icon size={size} strokeWidth={1.8}/>
function Shell(){const[path,setPath]=useState(location.pathname==='/'?'/dashboard':location.pathname),[open,setOpen]=useState(false);const{theme,setTheme}=useTheme();useEffect(()=>{if(location.pathname==='/')go('/dashboard');const cb=()=>setPath(location.pathname||'/dashboard');addEventListener('popstate',cb);return()=>removeEventListener('popstate',cb)},[]);const page=pages[path];return <div className="shell"><aside className={open?'open':''}><button className="close" aria-label="Close navigation" onClick={()=>setOpen(false)}><I icon={X} size={24}/></button><a className="brand" onClick={()=>go('/dashboard')}><b><I icon={Sparkles} size={22}/></b><span><strong>AI Study Assistant</strong><small>Learn. Plan. Achieve.</small></span></a><nav>{nav.map(({label,path:to,icon})=><a key={to} className={path===to?'active':''} onClick={()=>{go(to);setOpen(false)}}><i><I icon={icon}/></i>{label}</a>)}</nav><div className="quote">Small steps every day lead to big achievements. <b><I icon={Sparkles} size={18}/></b></div></aside><main><header><div><button className="hamburger" aria-label="Open navigation" onClick={()=>setOpen(true)}><I icon={Menu}/></button><h1>{path==='/dashboard'?'Good evening, Nagaveni':path==='/tasks'?'Your tasks':page?.[0]||'Settings'}</h1><p>{path==='/dashboard'?'Plan your day. Focus on what matters.':path==='/tasks'?'Keep your intentions clear and your momentum steady.':page?.[1]||'Personalize your study space.'}</p></div><div className="actions"><button aria-label="Select date"><I icon={CalendarDays} size={17}/><span>Fri, Aug 28, 2026</span><I icon={ChevronRight} size={16}/></button><button aria-label="Search"><I icon={Search}/></button><button aria-label="Notifications"><I icon={Bell}/></button><b className="avatar"><I icon={UserRound} size={19}/></b><span>Nagaveni</span></div></header>{path==='/dashboard'?<Dashboard onGo={go}/>:path==='/tasks'?<TaskManagerPage/>:path==='/daily-planner'?<DailyPlannerPage/>:path==='/dsa-tracker'?<DsaTrackerPage/>:path==='/settings'?<Settings theme={theme} setTheme={setTheme}/>:<Placeholder title={page?.[0]||'Daily Planner'} text={page?.[1]||''}/>}</main></div>}
function Dashboard({onGo}:{onGo:(x:string)=>void}){const[tasks,setTasks]=useState<Task[]>([]);useEffect(()=>{taskService.list().then(setTasks).catch(()=>{})},[]);const done=tasks.filter(x=>x.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;const taskIcons=[Sun,Code2,Clock3,BrainCircuit,BookOpen,FolderKanban];return <section className="dashboard"><div className="wide"><section className="hero"><div><small><I icon={Sparkles} size={15}/> Your plan for today</small><h2>Consistency is the key to success.</h2><p>{tasks.length?`You've got ${tasks.length} tasks waiting for you.`:'Your next focused session starts with one small step.'}</p></div><div className="ring" style={{'--p':pct} as React.CSSProperties}><b>{pct}%<small>Day Progress</small></b></div></section><section className="schedule"><div className="card-title"><h2><I icon={CalendarDays} size={18}/> Today's Schedule</h2><div><span>{done} / {tasks.length} tasks</span><button onClick={()=>onGo('/tasks')}><I icon={Plus} size={16}/> Add Task</button></div></div>{tasks.length?<div className="rows">{tasks.slice(0,7).map((t,i)=>{const TaskIcon=taskIcons[i%taskIcons.length];return <div className="taskrow" key={t.id}><time><Clock3 size={13}/> {new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(t.createdAt))}</time><article><i><TaskIcon size={20}/></i><div><b>{t.title}</b><small>{t.completed?'Completed and ready to celebrate':'A focused task for today'}</small></div><em className={t.completed?'done':''}>{t.completed?'Completed':'Upcoming'}</em><strong><MoreVertical size={18}/></strong></article></div>})}</div>:<div className="empty-state"><div className="empty-icon"><I icon={Sparkles} size={23}/></div><h2>Your schedule is open</h2><p>Add a task to give today a clear direction.</p></div>}</section></div><Widgets done={done} total={tasks.length}/></section>}
function Widgets({done,total}:{done:number;total:number}){const stats:[Icon,number,string][]=[[CheckCircle2,done,'Completed'],[Clock3,total-done,'In Progress'],[Timer,total-done,'Upcoming'],[ListChecks,total,'Total Tasks']];return <div className="widgets"><section><h2>August 2026 <small><ChevronLeft size={15}/><ChevronRight size={15}/></small></h2><div className="calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat','26','27','28','29','30','31','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'].map((x,i)=><b className={i===34?'today':i>6&&i<13?'muted':''} key={i}>{x}</b>)}</div></section><section><h2>Today's Overview</h2><div className="stats">{stats.map(([icon,value,label])=><div key={label}><i><I icon={icon} size={15}/></i><b>{value}</b><small>{label}</small></div>)}</div></section><section><h2>Upcoming Tasks <small>View all</small></h2>{['Design system update','DSA Contest','Project meeting'].map(x=><p className="upcoming" key={x}><Clock3 size={13}/><span><b>{x}</b><small>Tomorrow, 10:00 AM</small></span></p>)}</section><section><h2>Focus Time</h2><div className="focus"><Timer/><span><b>25:00</b><small>Start a Focus Session</small><button>Start</button></span></div></section></div>}
function Placeholder({title,text}:{title:string;text:string}){return <section className="module"><i><I icon={Sparkles} size={27}/></i><small>COMING NEXT</small><h2>{title}</h2><p>{text}</p><div>{['Thoughtfully designed','Built around you','Coming soon'].map((x,i)=><article key={x}><small>0{i+1}</small><b>{x}</b><p>This space is being shaped to support your study flow.</p></article>)}</div></section>}
function Settings({theme,setTheme}:{theme:Theme;setTheme:(x:Theme)=>void}){const opts:[Theme,Icon][]=[['light',Sun],['dark',Clock3],['system',SettingsIcon]];return <section className="module"><small>PERSONALIZE YOUR SPACE</small><h2>Settings</h2><p>Choose the appearance that feels most comfortable for your study sessions.</p><div>{opts.map(([x,icon])=><article className={theme===x?'selected':''} onClick={()=>setTheme(x)} key={x}><b><I icon={icon} size={18}/> {x[0].toUpperCase()+x.slice(1)}</b><p>{x==='system'?'Match your device':`Always use ${x} mode`}</p></article>)}</div></section>}
export default function App(){return <ThemeProvider><Shell/></ThemeProvider>}





